version: '3.8'

#You can start a single service with docker-compose up <service_name>
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./html:/usr/share/nginx/html

  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pg-data:/var/lib/postgresql/data

  webapp:
    image: jfahrer/demo_web_app:wait_for_pg
    depends_on:
      - pg
    ports:
      - 9292:9292
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST

  # stdin_open and tty is like the -it for docker container run when you want to start an interactive program e.g. sh
  alpine:
    image: alpine:latest
    stdin_open: true
    tty: true
    command: sh



volumes:
  pg-data: